### ISSUE TITLE
Feature: Set color scheme according to user's color

### ISSUE THREAD

**Issue by rhl-bthr** [sugarlabs/CowBulls-activity#3]
The color scheme of the game(activity) should have some resemblence to the sugar user's color.

**Possible areas:**
 - `entries.png` can be replaced with a line of user's color
 - `highlight.png` can also be changed to first color
 - Background can be the second color of the user.

**Comment by rhl-bthr** [comment]
This issue was pointed again, in this activity's review.

I agree with the idea that an activity should have some color similarity with the user's icon colors.

Hence, I tried using the background as the first and second color of the user, for multiple user colors.

I felt that the activity looked simple in design(personal view) with the original background(453a383), and wasn't very appealing with darker or glossier colors, that came up in some cases of using user's colors(c92ed79)

Please suggest @walterbender, @quozl

**Comment by quozl** [comment]
Display background is not the best thing to change to the user colours, if there are other things that may change.  Looking at the screenshots, perhaps some of the icons may be coloured.  I haven't reviewed the activity function; but if any of those icons might represent the user, they would be my first choice.  If there are no icons that represent the user, I don't think the user colours need to be used; there are other activities (such as Clock, Jukebox, Read, ImageViewer) that don't use any user colours.

**Comment by rhl-bthr** [comment]
None of the icons represent the user. So, for now, I will go with no user colors.

A user Icon could be an addition to make the activity more interactive.

Thank you @quozl
